[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
httpPort = 8080  # Cambia esto al puerto que Railway está usando
internalPort = 8080  # Cambia esto también